### ISSUE TITLE
Using format loggers in unit tests

### ISSUE THREAD

**Issue by mohlerm** [NServiceBusExtensions/NServiceBus.Serilog#18]
Hi

We use NServiceBus.Serilog in combination with NServiceBus 7.
Similarly to the example given in https://github.com/NServiceBusExtensions/NServiceBus.Serilog/blob/master/Sample/CreateUserHandler.cs we want to log an ID in a handler as follows:
`logger.InfoFormat(@"ExampleIdId={ExampleId},", message.ExampleId);`
This works fine and I receive a nice json with this property.

However, when running the handler in a fluent style unit tests I receive the following error:

> Message: System.FormatException : Input string was not in a correct format.

Switching it to a valid 'format string' like
`logger.InfoFormat(@"ExampleIdId={0},", message.ExampleId);`
works again but kinda defeats the purpose.

To me it seems like the ILog interface used in unit tests validates the input string, while the using the format loggers in NServiceBus.Serilog forwards it to serilog which happily accepts these kind of format strings.

Is there anything I can do here? I guess I could put one more level of abstraction in the logger and mock ILog for the unit tests. However that seems like unnesseary overhead to me...

Cheers

**Comment by SimonCropp** [comment]
@mohlerm that sample was wrong. you should be using the Serilog Ilogger and not the NSB ILog. https://github.com/NServiceBusExtensions/NServiceBus.Serilog/commit/307550300b7d7b52ff65038c9da41b84953ea68b

**Comment by mohlerm** [comment]
@SimonCropp Thank you for your answer.
The solution seems a bit subpar to me. When using Serilogs ILogger I loose the ability to easily switch out the logging framework. Of course, one can argue about the need for this but we actually switched from Log4net to Serilog and due to this it was rather painless.

**Comment by SimonCropp** [comment]
the NSB logging API was never meant to be a logging abstraction for business code (handlers and sagas etc). it was only meant as an abstraction for the internal NSB components, and other extensions to NSB that  aslo do not want to take a dependency on a logging framework.

Business code should leverage the full feature set of the chose logging framework. if you do no do this then you are forgoing much value. in the serilog context, if you use the NSB logging abstraction, you cannot use

 * [property enrichment](https://github.com/serilog/serilog/wiki/Enrichment#the-logcontext)
 * [scoping](https://nblumhardt.com/2016/11/ilogger-beginscope/)
 * [Serilog Roslyn analysis](https://github.com/Suchiman/SerilogAnalyzer)

having said that if you still want remain using the NSB logging abstraction...

i would assume in your test code you are not calling setting the logmanager to serilog? if this is the case then it will default to the normal NSB logger, and hence u r getting a format error. to get around this i would suggest requesting of the particular team that they add a "testingLogManager" to [NServiceBus.Testing](https://docs.particular.net/nservicebus/testing/) project. it could use this approach https://docs.particular.net/samples/logging/custom-factory/ and you could then write something like `LogManager.Use<TestLoggerDefinition>();` in your test startup code. in the short term you could implement your own TestLoggerDefinition

**Comment by SimonCropp** [comment]
I should also point out if your desired outcome of "using the nsb logging abstraction" is to "make it easier to switch to a diff logging library in the future", you have not achieved that. or to be more specific you have a false perception that you are making it easier. 

the reason is you have abstracted away the part that is easy to change. ie the strong typed .net api for constructing a logger instance. when switching to a diff logging lib changing that api is relatively simple to migrate over, it can mostly be done with some targeted search and replaces and regex. 

however you have leaked in something that is harder to migrate over, that being the implementation details of the serilog interpolation/property syntax. this is illustrated by the exact issue you are experiencing in this issue. take your log statement `@"ExampleIdId={ExampleId},", message.ExampleId`. if you move to another log lib there is no guarantee it will accept the same syntax, and that will most likely only manifest at runtime when the log statement is executed. you would likely get a very similar effort to the on when u user that syntax in your unit test. 

to ensure u can switch in the future you would need to stick to the standard .net string format approach, which would significantly decrease the value of using serilog. it would also leave you suffering from the logging lib equivalent of the [Conforming Container anti-pattern](http://blog.ploeh.dk/2014/05/19/conforming-container/)

**Comment by SimonCropp** [comment]
Seems particular already has the facility to mock the logging functionality, it is not documented 
https://github.com/Particular/docs.particular.net/issues/3971#issuecomment-414279982

So will close this one, since nothing needs to happen in this repo

**Comment by SimonCropp** [comment]
FYI i have some proposed change in the licensing model for NuGet packages under the NServiceBusExtensions Org https://discuss.particular.net/t/proposed-change-in-the-licensing-model-for-nuget-packages-under-the-nservicebusextensions-org
